{
  pkgs,
  lib,
  config,
  ...
}:

let
  user = "alsoasnerd";
  baseDir = "/home/${user}/Documents/Library";
  stateDir = "${baseDir}/bookorbit";
  appUrl = "http://bookorbit.home.arpa";

in
{
  sops.secrets."services/bookorbit/postgres_password" = {
    sopsFile = ../../secrets/services.yaml.sops;
  };
  sops.secrets."services/bookorbit/jwt_secret" = {
    sopsFile = ../../secrets/services.yaml.sops;
  };
  sops.secrets."services/bookorbit/podcast_encryption_key" = {
    sopsFile = ../../secrets/services.yaml.sops;
  };
  sops.secrets."services/bookorbit/setup_bootstrap_token" = {
    sopsFile = ../../secrets/services.yaml.sops;
  };

  virtualisation.oci-containers.containers."bookorbit" = {
    image = "ghcr.io/bookorbit/bookorbit:latest";
    environment = {
      APP_URL = appUrl;
      CLIENT_URL = appUrl;
      BOOK_DOCK_PATH = "/bookdrop";
      LIBRARY_BROWSE_ROOT = "/books";
      POSTGRES_DB = "bookorbit";
      POSTGRES_HOST = "bookorbit-db";
      POSTGRES_PORT = "5432";
      POSTGRES_USER = "bookorbit";
      PGID = "1000";
      PUID = "1000";
      TZ = "America/Sao_Paulo";
    };
    environmentFiles = [
      config.sops.secrets."services/bookorbit/postgres_password".path
      config.sops.secrets."services/bookorbit/jwt_secret".path
      config.sops.secrets."services/bookorbit/podcast_encryption_key".path
      config.sops.secrets."services/bookorbit/setup_bootstrap_token".path
    ];
    volumes = [
      "${baseDir}/books:/books:rw"
      "${baseDir}/bookdrop:/bookdrop:rw"
      "${stateDir}/app:/data:rw"
    ];
    ports = [
      "6060:3000/tcp"
    ];
    dependsOn = [
      "bookorbit-db"
    ];
    log-driver = "journald";
    extraOptions = [
      "--cap-add=CHOWN"
      "--cap-add=DAC_OVERRIDE"
      "--cap-add=FOWNER"
      "--cap-add=SETGID"
      "--cap-add=SETUID"
      "--cap-drop=ALL"
      "--read-only"
      "--tmpfs=/tmp"
      "--security-opt=no-new-privileges:true"
      "--stop-timeout=30"
      "--health-cmd=wget -q -T 4 -O /dev/null http://localhost:3000/api/v1/health"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=20s"
      "--health-timeout=5s"
      "--network-alias=bookorbit"
      "--network=bookorbit_default"
    ];
  };

  virtualisation.oci-containers.containers."bookorbit-db" = {
    image = "pgvector/pgvector:pg18";
    environment = {
      PGDATA = "/var/lib/postgresql/data/pgdata";
      POSTGRES_DB = "bookorbit";
      POSTGRES_USER = "bookorbit";
    };
    environmentFiles = [
      config.sops.secrets."services/bookorbit/postgres_password".path
    ];
    volumes = [
      "${stateDir}/postgres:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -U bookorbit -d bookorbit"
      "--health-interval=10s"
      "--health-retries=10"
      "--health-start-period=20s"
      "--health-timeout=5s"
      "--network-alias=bookorbit-db"
      "--network=bookorbit_default"
    ];
  };

  systemd.services."podman-bookorbit" = {
    preStart = ''
      mkdir -p ${stateDir}/app ${baseDir}/books ${baseDir}/bookdrop
      chown 1000:1000 ${stateDir}/app ${baseDir}/books ${baseDir}/bookdrop
    '';
    serviceConfig.Restart = lib.mkOverride 90 "always";
    after = [ "podman-network-bookorbit_default.service" ];
    requires = [ "podman-network-bookorbit_default.service" ];
    partOf = [ "podman-compose-bookorbit-root.target" ];
    wantedBy = [ "podman-compose-bookorbit-root.target" ];
  };

  systemd.services."podman-bookorbit-db" = {
    preStart = ''
      mkdir -p ${stateDir}/postgres
      chown 999:999 ${stateDir}/postgres
    '';
    serviceConfig.Restart = lib.mkOverride 90 "always";
    after = [ "podman-network-bookorbit_default.service" ];
    requires = [ "podman-network-bookorbit_default.service" ];
    partOf = [ "podman-compose-bookorbit-root.target" ];
    wantedBy = [ "podman-compose-bookorbit-root.target" ];
  };

  systemd.services."podman-network-bookorbit_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f bookorbit_default";
    };
    script = ''
      podman network inspect bookorbit_default || podman network create bookorbit_default
    '';
    partOf = [ "podman-compose-bookorbit-root.target" ];
    wantedBy = [ "podman-compose-bookorbit-root.target" ];
  };

  systemd.targets."podman-compose-bookorbit-root" = {
    unitConfig.Description = "Root target generated by compose2nix.";
    wantedBy = [ "multi-user.target" ];
  };

  systemd.tmpfiles.rules = [
    "d ${baseDir}/books 0755 ${user} users - -"
    "d ${baseDir}/bookdrop 0755 ${user} users - -"
    "d ${stateDir} 0755 ${user} users - -"
    "d ${stateDir}/app 0755 ${user} users - -"
    "d ${stateDir}/postgres 0700 999 999 - -"
  ];
}
