{
  pkgs,
  lib,
  config,
  ...
}:

let
  user = "alsoasnerd";
  baseDir = "/home/${user}/Documents/Library";

in
{
  sops.secrets."services/grimmory/db_password" = {
    sopsFile = ../../secrets/services.yaml.sops;
  };
  sops.secrets."services/grimmory/mariadb_password" = {
    sopsFile = ../../secrets/services.yaml.sops;
  };

  virtualisation.oci-containers.containers."grimmory" = {
    image = "grimmory/grimmory:latest";
    environment = {
      API_DOCS_ENABLED = "true";
      DATABASE_URL = "jdbc:mariadb://mariadb:3306/grimmory";
      DATABASE_USERNAME = "alsoasnerd";
      DISK_TYPE = "local";
      GROUP_ID = "1000";
      TZ = "America/Sao_Paulo";
      USER_ID = "1000";
    };
    environmentFiles = [
      config.sops.secrets."services/grimmory/db_password".path
    ];
    volumes = [
      "${baseDir}/bookdrop:/bookdrop:rw"
      "${baseDir}/books:/books:rw"
      "${baseDir}/data:/app/data:rw"
    ];
    ports = [
      "6060:6060/tcp"
    ];
    dependsOn = [
      "mariadb"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=wget -q -O - http://localhost:6060/api/v1/healthcheck"
      "--health-interval=1m0s"
      "--health-retries=5"
      "--health-start-period=1m0s"
      "--health-timeout=10s"
      "--network-alias=grimmory"
      "--network=grimmory_default"
    ];
  };

  virtualisation.oci-containers.containers."mariadb" = {
    image = "lscr.io/linuxserver/mariadb:11.4.5";
    environment = {
      MYSQL_DATABASE = "grimmory";
      MYSQL_USER = "alsoasnerd";
      PGID = "1000";
      PUID = "1000";
      TZ = "America/Sao_Paulo";
    };
    environmentFiles = [
      config.sops.secrets."services/grimmory/mariadb_password".path
    ];
    volumes = [
      "${baseDir}/mariadb/config:/config:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"mariadb-admin\", \"ping\", \"-h\", \"localhost\"]"
      "--health-interval=5s"
      "--health-retries=10"
      "--health-timeout=5s"
      "--network-alias=mariadb"
      "--network=grimmory_default"
    ];
  };

  systemd.services."podman-grimmory" = {
    preStart = ''
      mkdir -p ${baseDir}/data ${baseDir}/books ${baseDir}/bookdrop
      chown -R 1000:1000 ${baseDir}/data ${baseDir}/books ${baseDir}/bookdrop
    '';
    serviceConfig.Restart = lib.mkOverride 90 "always";
    after = [ "podman-network-grimmory_default.service" ];
    requires = [ "podman-network-grimmory_default.service" ];
    partOf = [ "podman-compose-grimmory-root.target" ];
    wantedBy = [ "podman-compose-grimmory-root.target" ];
  };

  systemd.services."podman-mariadb" = {
    preStart = ''
      mkdir -p ${baseDir}/mariadb/config
      chown -R 1000:1000 ${baseDir}/mariadb/config
    '';
    serviceConfig.Restart = lib.mkOverride 90 "always";
    after = [ "podman-network-grimmory_default.service" ];
    requires = [ "podman-network-grimmory_default.service" ];
    partOf = [ "podman-compose-grimmory-root.target" ];
    wantedBy = [ "podman-compose-grimmory-root.target" ];
  };

  systemd.services."podman-network-grimmory_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f grimmory_default";
    };
    script = ''
      podman network inspect grimmory_default || podman network create grimmory_default
    '';
    partOf = [ "podman-compose-grimmory-root.target" ];
    wantedBy = [ "podman-compose-grimmory-root.target" ];
  };

  systemd.targets."podman-compose-grimmory-root" = {
    unitConfig.Description = "Root target generated by compose2nix.";
    wantedBy = [ "multi-user.target" ];
  };

  systemd.tmpfiles.rules = [
    "D ${baseDir}/mariadb/config 0755 ${user} users - -"
    "D ${baseDir}/data 0755 ${user} users - -"
    "D ${baseDir}/books 0755 ${user} users - -"
    "D ${baseDir}/bookdrop 0755 ${user} users - -"
  ];
}
